"use strict";

var app = angular.module('vixis', ['angularplasmid']);

app.controller('plasmidCtrl', ['$http', '$scope', '$timeout', function plasmidCtrl ($http, $scope, $timeout) {

    $scope.sequence = "AACGCTGAAACTGTATGCTCGCAAACAGCTGTGAAGTCGCGGGTTTTAAATTACCAATCCTAAATGATAGATCTAGATCTAGATCTAGATTATCTTCACTAGATAAATTTGAGTGTTTTTACTAAGTTTTTATTTGGTGATTACTAAAATTTAAATTCTTAGTCAAATCCAAAATGGTAATAATAGCCCCCTGCAAAACTCGTTAGGAATGCGTCCATGCGAAAAGAGAGTTGCCACATGCGCGCAAAAATAATGAACATAGGTGTGTCAGCTGAGCGGTATTGGTGGAATTCAATTTTGGCTTTTTCATGCTTTTAAACGATTAAAAATGACCCGCGATGAGGATAATGGTTTTAGTGAATGGGTAAGATGTAGATAAAATGCTAAAAACATTGTACATAAACCAAACCTGCTCTTTTCAGGGCGGCTACTTCGAAGCCAAGAAATCTAAACTTGAGGAGCAGTTCGCTGCCGCCAGCGATCCATTTCGCAAGTCGGACCTCTTCCAAGGAATTTCTATATTTGTGAACGGCCGGACTGACCCTTCGGCGGATGAACTGAAGCGTATTATGATGGTGCACGGCGGGACCTTTCACCACTACGAAAGGAGCCACACGACGTACATAATAGCCTCCGTTCTGCCCGATGTGAAGGTCAGGAACATGAATCTCAGCAAGTTCATCAGCGCCAAGTGGGTGGTGGATTGTCTGGAGAAAAAGAAGATAGTAGACTACAAACCCTATCTGCTGTACACGAACCAGAAGACATCGCAGCCCATGCTCATCTTTGGGAAACCCAAAGACAACGGCGCAAATGAGAGCAAATCGGATGTGGAGCCGCCGAAAGATAAAGCGGAAGTGGAAGTAGACTCTACAAAAGATGAAACGCAAATGGAGTTGGGTGGCATTCTCAAGAATTTGCAGCAGGCTGTGGCCACTTCGCCGGAAAAGGAGGCCAGTGCATCAGAGAGCAAGATCACAAACTTATCCACCACCTCGAG";

    $scope.featurePos = 216;

    $scope.sequenceRegion = {
        start : 802,
        end : 980
    };

    $scope.featureMarkers = [
        {start : 482, end : 567, text : 'LEUII'},
        {start : 585, end : 645, text : 'AMPR'},
        {start : 661, end : 692, text : 'ADHI'}
    ];

    $scope.featureStart = $scope.featureMarkers[0].start - 20;
    $scope.featureEnd = $scope.featureMarkers[$scope.featureMarkers.length-1].end + 20;

    $scope.markerClick = function(event, marker){
        console.log(" >> ", marker, marker);
        $scope.$apply(function(){
            $scope.selectedmarker = marker;
        });
    }

    $scope.dismissPopup = function(){
        $scope.selectedmarker = null;
    }


}]);
